# Generated by Django 4.2.5 on 2023-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Description', max_length=255),
        ),
    ]
